### ISSUE TITLE
RUN SCRIPT should report failing input statement

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1638]
Per #1637, KSQL just throws an error, with no indication of which statement caused it. 

```
ksql> RUN SCRIPT '/data/examples.sql';
io.confluent.ksql.util.KsqlException: Stream-Stream joins must have a WITHIN clause specified. None was provided. To learn about how to specify a WITHIN clause with a stream-stream join, please visit: https://docs.confluent.io/current/ksql/docs/syntax-reference.html#create-stream-as-select

```
RUN SCRIPT should report failing input statement to make it easier to debug.

**Comment by big-andy-coates** [comment]
This is likely fixed by https://github.com/confluentinc/ksql/pull/2434

**Comment by big-andy-coates** [comment]
Would you mind testing and closing if you're happy?

**Comment by spena** [comment]
This is not fixed yet. I run a script with a CSAS statement and it fails with:

```
$ ../confluent-5.4.0-SNAPSHOT/bin/ksql <<EOF
RUN SCRIPT '/tmp/app.sql';
EOF
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Oct 24, 2019 3:28:41 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
KSQL, Copyright 2017-2019 Confluent Inc.

CLI v5.4.0-SNAPSHOT, Server v5.4.0-SNAPSHOT located at http://localhost:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> line 1:18: mismatched input '\' expecting ';'
ksql> Exiting KSQL.
```

Clearly not feedback about what command failed.
