### ISSUE TITLE
ksql-streams Compilation Error

### ISSUE THREAD

**Issue by jmilagroso** [confluentinc/ksql#4610]
**Describe the bug**
ksql-master/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[29,32] cannot find symbol
  symbol:   class StoreQueryParameters
  location: package org.apache.kafka.streams

**To Reproduce**
Steps to reproduce the behavior, include:
1. Download https://github.com/confluentinc/ksql/archive/master.zip
2. unzip ksql-master.zip
3. cd ksql-master
4. mvn clean compile install -DskipTests
or
1. git clone git@github.com:confluentinc/ksql.git
2. cd ksql
3. mvn clean compile install -DskipTests 

**Expected behavior**
It should compile successfully.

**Actual behaviour**
Compile error:
```sh
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /opt/techstack/ksql-master/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[29,32] cannot find symbol
  symbol:   class StoreQueryParameters
  location: package org.apache.kafka.streams
[ERROR] /opt/techstack/ksql-master/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[78,13] cannot find symbol
  symbol:   variable StoreQueryParameters
  location: class io.confluent.ksql.execution.streams.materialization.ks.KsStateStore
[ERROR] /opt/techstack/ksql-master/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[83,13] cannot find symbol
  symbol:   variable StoreQueryParameters
  location: class io.confluent.ksql.execution.streams.materialization.ks.KsStateStore
[INFO] 3 errors 
```

**Comment by jmilagroso** [comment]
Renaming `StoreQueryParameters` to `StoreQueryParams` on the following files

```sh
ksql/ksql-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStoreTest.java
ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java
```

fixes the error and able to compile successfully.

**Comment by colinhicks** [comment]
Thanks for reporting this, @jmilagroso!

Closing the loop here as this was addressed in e0eb35684b40226c670729d80fb3da60d9dcaef0.

**Comment by jmilagroso** [comment]
hi @colinhicks , i tried cloning the ksql master branch today (Feb 28 2020 11am PHT) and I still get the  error.
```sh
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[29,32] cannot find symbol
  symbol:   class StoreQueryParameters
  location: package org.apache.kafka.streams
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[78,13] cannot find symbol
  symbol:   variable StoreQueryParameters
  location: class io.confluent.ksql.execution.streams.materialization.ks.KsStateStore
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[83,13] cannot find symbol
  symbol:   variable StoreQueryParameters
  location: class io.confluent.ksql.execution.streams.materialization.ks.KsStateStore
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ksql-parent 6.0.0-SNAPSHOT:
[INFO] 
[INFO] ksql-parent ........................................ SUCCESS [ 23.569 s]
[INFO] ksql-test-util ..................................... SUCCESS [ 38.102 s]
[INFO] ksql-udf ........................................... SUCCESS [  5.552 s]
[INFO] ksql-common ........................................ SUCCESS [ 32.043 s]
[INFO] KSQL UDF / UDAF :: Quickstart ...................... SUCCESS [  8.911 s]
[INFO] ksql-serde ......................................... SUCCESS [ 22.388 s]
[INFO] ksql-rest-model .................................... SUCCESS [ 17.030 s]
[INFO] ksql-execution ..................................... SUCCESS [ 13.358 s]
[INFO] ksql-metastore ..................................... SKIPPED
[INFO] ksql-parser ........................................ SKIPPED
[INFO] ksql-streams ....................................... FAILURE [  1.292 s]
[INFO] ksql-engine ........................................ SKIPPED
[INFO] ksql-tools ......................................... SUCCESS [ 10.797 s]
[INFO] ksql-rest-client ................................... SKIPPED
[INFO] ksql-version-metrics-client ........................ SKIPPED
[INFO] ksql-rest-app ...................................... SKIPPED
[INFO] ksql-cli ........................................... SKIPPED
[INFO] ksql-examples ...................................... SKIPPED
[INFO] ksql-console-scripts ............................... SUCCESS [  6.146 s]
[INFO] ksql-etc ........................................... SUCCESS [  6.162 s]
[INFO] ksql-functional-tests .............................. SKIPPED
[INFO] ksql-package ....................................... SKIPPED
[INFO] ksql-benchmark ..................................... SKIPPED
[INFO] KSQL RocksDB Config Setter ......................... SUCCESS [ 28.495 s]
[INFO] ksql-docker ........................................ SKIPPED
[INFO] ksql-api-reactive-streams-tck ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:17 min (Wall Clock)
[INFO] Finished at: 2020-02-28T11:15:26+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project ksql-streams: Compilation failure: Compilation failure: 
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[29,32] cannot find symbol
[ERROR]   symbol:   class StoreQueryParameters
[ERROR]   location: package org.apache.kafka.streams
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[78,13] cannot find symbol
[ERROR]   symbol:   variable StoreQueryParameters
[ERROR]   location: class io.confluent.ksql.execution.streams.materialization.ks.KsStateStore
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[83,13] cannot find symbol
[ERROR]   symbol:   variable StoreQueryParameters
[ERROR]   location: class io.confluent.ksql.execution.streams.materialization.ks.KsStateStore
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ksql-streams
```

$ git log
```sh
commit 473d82954f522eba9b67a4e39165b3e561ff188c (HEAD -> master, origin/master, origin/HEAD)
Merge: 6fcd05b26 d692e2411
Author: Steven Zhang <stevenz@confluent.io>
Date:   Thu Feb 27 17:35:23 2020 -0800

    Merge branch '5.5.x'

commit d692e2411708f992c708a65061c67a4cad593ed0 (origin/5.5.x)
Author: Steven Zhang <stevenz@confluent.io>
Date:   Thu Feb 27 16:16:32 2020 -0800

    fix: terminate CTAS after running integration test

commit 6fcd05b2662e8c43110407b1193aaa30094dcee2
Merge: ba4fe7456 5efc0805f
Author: Almog Gavra <almog@confluent.io>
Date:   Thu Feb 27 15:04:02 2020 -0800

    Merge branch '5.5.x'

commit 5efc0805f9b3d16a71ee50e70ef7f3c7c8217c3c
Merge: 6d7665feb 8168002a8
Author: Almog Gavra <almog@confluent.io>
Date:   Thu Feb 27 15:02:09 2020 -0800

    Merge branch '5.4.x' into 5.5.x
```

**Comment by colinhicks** [comment]
Hi, @jmilagroso – I apologize for closing this issue before you verified you could build successfully!

I wonder if you have some out-of-date artifacts cached in your local maven repository, which are causing the reported failure.

Could you try rebuilding with `mvn -U clean install`?

Separately, I verified that I could start from scratch and build the project without issues with the following commands. This eliminates the possibility that my settings or local m2 is interfering, but I don't recommend trying it, as it takes a very long time to fetch fresh dependencies.

```
$ git clone git@github.com:confluentinc/ksql.git
```
```
$ echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                       https://maven.apache.org/xsd/settings-1.0.0.xsd"></settings>' > empty-settings.xml
```
```
$ mvn -s empty-settings.xml -U clean install -DskipTests -Dspotbugs.skip -Dcheckstyle.skip -Dmaven.repo.local=../temp-repo
```
```
<snip>
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46:32 min
[INFO] Finished at: 2020-02-28T14:55:27-05:00
```

In the meantime, I will re-open the issue. Let's close it when you can indeed build the project :)

**Comment by jmilagroso** [comment]
hi @colinhicks ,

```sh
$ mvn -U clean install
```
produces
```sh
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[83,13] cannot find symbol
  symbol:   variable StoreQueryParameters
  location: class io.confluent.ksql.execution.streams.materialization.ks.KsStateStore
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ksql-parent 6.0.0-SNAPSHOT:
[INFO] 
[INFO] ksql-parent ........................................ SUCCESS [  6.282 s]
[INFO] ksql-test-util ..................................... SUCCESS [ 15.513 s]
[INFO] ksql-udf ........................................... SUCCESS [  2.059 s]
[INFO] ksql-common ........................................ SUCCESS [ 28.386 s]
[INFO] KSQL UDF / UDAF :: Quickstart ...................... SUCCESS [ 32.973 s]
[INFO] ksql-serde ......................................... SUCCESS [ 18.680 s]
[INFO] ksql-rest-model .................................... SUCCESS [ 12.081 s]
[INFO] ksql-execution ..................................... SUCCESS [ 13.467 s]
[INFO] ksql-metastore ..................................... SUCCESS [  8.015 s]
[INFO] ksql-parser ........................................ SUCCESS [ 18.597 s]
[INFO] ksql-streams ....................................... FAILURE [  0.708 s]
[INFO] ksql-engine ........................................ SKIPPED
[INFO] ksql-tools ......................................... SKIPPED
[INFO] ksql-rest-client ................................... SKIPPED
[INFO] ksql-version-metrics-client ........................ SKIPPED
[INFO] ksql-rest-app ...................................... SKIPPED
[INFO] ksql-cli ........................................... SKIPPED
[INFO] ksql-examples ...................................... SKIPPED
[INFO] ksql-console-scripts ............................... SKIPPED
[INFO] ksql-etc ........................................... SKIPPED
[INFO] ksql-functional-tests .............................. SKIPPED
[INFO] ksql-package ....................................... SKIPPED
[INFO] ksql-benchmark ..................................... SKIPPED
[INFO] KSQL RocksDB Config Setter ......................... SKIPPED
[INFO] ksql-docker ........................................ SKIPPED
[INFO] ksql-api-reactive-streams-tck ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:41 min
[INFO] Finished at: 2020-03-02T10:33:43+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project ksql-streams: Compilation failure: Compilation failure: 
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[29,32] cannot find symbol
[ERROR]   symbol:   class StoreQueryParameters
[ERROR]   location: package org.apache.kafka.streams
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[78,13] cannot find symbol
[ERROR]   symbol:   variable StoreQueryParameters
[ERROR]   location: class io.confluent.ksql.execution.streams.materialization.ks.KsStateStore
[ERROR] /usr/share/nginx/html/ksql/ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java:[83,13] cannot find symbol
[ERROR]   symbol:   variable StoreQueryParameters
[ERROR]   location: class io.confluent.ksql.execution.streams.materialization.ks.KsStateStore
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ksql-streams

```

```sh
$ git log
commit ce74cf899d9d8ce17a57a184593c9743fcc4817b (HEAD -> master, origin/master, origin/HEAD)
Author: Rohan <desai.p.rohan@gmail.com>
Date:   Sat Feb 29 16:51:21 2020 -0800

    fix: change configOverrides back to streamsProperties (#4675)
    
    * fix: change configOverrides back to streamsProperties
    
    Revert the breaking api change
    
    * fix: missed annotation

commit 9079fc0046e8a5de25dff1abd3bc4dba97f38092
Merge: 2898b908c 7e625ecc2
Author: Almog Gavra <almog@confluent.io>
Date:   Fri Feb 28 14:54:52 2020 -0800

    Merge branch '5.5.x'

commit 7e625ecc25afc52601c6a667f803415a6bae16b4 (origin/5.5.x)
Author: Robert Yokota <ryokota@confluent.io>
Date:   Fri Feb 28 14:50:29 2020 -0800

    chore: Remove use of deprecated Jackson API (#4671)
    
    Co-authored-by: Almog Gavra <almog@confluent.io>

commit 2898b908c3f30ed0ea4d3666718c48cf979188ee
Merge: c4ee823f6 332c04a4a
Author: Almog Gavra <almog@confluent.io>
Date:   Fri Feb 28 12:26:10 2020 -0800

```

**Comment by jmilagroso** [comment]
I'll try building it from scratch see what happens..

**Comment by jmilagroso** [comment]
```sh
$ mvn -T 1C -s empty-settings.xml -U clean install -DskipTests -Dspotbugs.skip -Dcheckstyle.skip -Dmaven.repo.local=../temp-repo
```
produces
```sh
Downloaded from central: https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.9.0/byte-buddy-1.9.0.jar (3.2 MB at 117 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.jar (5.3 MB at 166 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ksql-parent 6.0.0-SNAPSHOT:
[INFO] 
[INFO] ksql-parent ........................................ SUCCESS [10:41 min]
[INFO] ksql-test-util ..................................... FAILURE [03:16 min]
[INFO] ksql-udf ........................................... SKIPPED
[INFO] ksql-common ........................................ SKIPPED
[INFO] KSQL UDF / UDAF :: Quickstart ...................... SUCCESS [03:02 min]
[INFO] ksql-serde ......................................... SKIPPED
[INFO] ksql-rest-model .................................... SKIPPED
[INFO] ksql-execution ..................................... SKIPPED
[INFO] ksql-metastore ..................................... SKIPPED
[INFO] ksql-parser ........................................ SKIPPED
[INFO] ksql-streams ....................................... SKIPPED
[INFO] ksql-engine ........................................ SKIPPED
[INFO] ksql-tools ......................................... SKIPPED
[INFO] ksql-rest-client ................................... SKIPPED
[INFO] ksql-version-metrics-client ........................ SKIPPED
[INFO] ksql-rest-app ...................................... SKIPPED
[INFO] ksql-cli ........................................... SKIPPED
[INFO] ksql-examples ...................................... SKIPPED
[INFO] ksql-console-scripts ............................... SUCCESS [01:02 min]
[INFO] ksql-etc ........................................... SUCCESS [01:02 min]
[INFO] ksql-functional-tests .............................. SKIPPED
[INFO] ksql-package ....................................... SKIPPED
[INFO] ksql-benchmark ..................................... SKIPPED
[INFO] KSQL RocksDB Config Setter ......................... SKIPPED
[INFO] ksql-docker ........................................ SKIPPED
[INFO] ksql-api-reactive-streams-tck ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14:01 min (Wall Clock)
[INFO] Finished at: 2020-03-02T10:53:42+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ksql-test-util: Could not resolve dependencies for project io.confluent.ksql:ksql-test-util:jar:6.0.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:kafka_2.12:jar:5.5.0-ccs-SNAPSHOT, org.apache.kafka:kafka_2.12:jar:test:5.5.0-ccs-SNAPSHOT, org.apache.kafka:kafka-clients:jar:test:5.5.0-ccs-SNAPSHOT: Could not transfer artifact org.apache.kafka:kafka_2.12:jar:5.5.0-ccs-SNAPSHOT from/to confluent-snapshots (https://s3-us-west-2.amazonaws.com/confluent-snapshots/): s3-us-west-2.amazonaws.com: Unknown host s3-us-west-2.amazonaws.com -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ksql-test-util
```
